version: '3.8'

services:
  vue3-app:
    container_name: vue3-app
    build:
      context: ./vue3-typescript-app
      dockerfile: ./Dockerfile
    command: yarn serve
    volumes:
      - ./vue3-typescript-app:/app
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
  cypress:
    container_name: cypress
    image: 'cypress/included:3.4.0'
    depends_on:
      - vue3-app
    environment:
      - CYPRESS_baseUrl=http://vue3-app:8080
    working_dir: /e2e
    volumes:
      - ./vue3-typescript-app:/e2e
    profiles:
      - e2e